settings:
  name: Cloud Volumes Service for Google Cloud
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: bluexp-relnotes  
sidebar:
  entries:
    - title: Cloud Volumes Service for Google Cloud docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Cloud Volumes Service for Google Cloud
          url: /concept-cvs-gcp.html
        - title: Getting started workflow
          url: /task-quick-start.html
        - title: Set up Google Cloud
          url: /task-set-up-google-cloud.html
        - title: Create a working environment
          url: /task-create-working-env.html
    - title: Use Cloud Volumes Service for Google Cloud
      entries:
        - title: Create and mount volumes
          url: /task-create-volumes.html
        - title: Manage existing volumes
          url: /task-manage-volumes.html
        - title: Manage cloud volumes snapshots
          url: /task-manage-snapshots.html
        - title: Manage your Active Directory configuration
          url: /task-manage-active-directory.html
        - title: Remove Cloud Volumes Service
          url: /task-remove-working-env.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family

